export const fooditems = [
  {
    foodicon: "🧀",
    title: "Cheese",
    description: "diary product",
    primary: "!",
    timeleft: "4h",
    timeadded: "",
    alert: true,
  },
  {
    foodicon: "🥦",
    title: "broccoli",
    description: "vegetable",
    primary: "!",
    timeleft: "2d",
    timeadded: "",
    alert: true,
  },
  {
    foodicon: "🍇",
    title: "grape",
    description: "fruit",
    primary: "",
    timeleft: "4h",
    timeadded: "",
    alert: false,
  },
  {
    foodicon: "🌽",
    title: "corn",
    description: "grain and cereal",
    primary: "",
    timeleft: "1w",
    timeadded: "",
    alert: false,
  },
  {
    foodicon: "	🍎",
    title: "apple",
    description: "fruit",
    primary: "!",
    timeleft: "1w",
    timeadded: "",
    alert: true,
  },
  {
    foodicon: "🥕",
    title: "carrot",
    description: "vegetable",
    primary: "!",
    timeleft: "2w",
    timeadded: "",
    alert: true,
  },
  {
    foodicon: "🍊",
    title: "orange",
    description: "fruit",
    primary: "!",
    timeleft: "3w",
    timeadded: "",
    alert: false,
  },
];
